### ISSUE TITLE
Amazon Connect Hours of Operation: Multiple Timezones?

### ISSUE THREAD

**Issue by nelsonic** [awsdocs/amazon-connect-admin-guide#24]
Greetings fellow Amazon Connectors! 👋 

We've setup an Amazon Connect instance for a company that operates in multiple timezones.
When defining the Hours of operation, I appear to only be allowed to use **_one_ time zone**:
<img width="1014" alt="amazon-connect-one-timezone" src="https://user-images.githubusercontent.com/194400/133248465-4426d4c0-18a0-4958-be86-0ea83eceef96.png">

I've read through the docs online [https://github.com/awsdocs/amazon-connect-admin-guide/blob/master/doc_source/set-hours-operation.md](https://github.com/awsdocs/amazon-connect-admin-guide/blob/c746a0529247f5b2f5d46dec0668bdce1540bb6a/doc_source/set-hours-operation.md) and done a bit of googling but not been able to find an answer.

We would like to have multiple tables with different timezones or gain an understanding of how companies that operate in multiple timezones manage their Connect Hours of Operation.

Thanks.

Note: this question is cross-posted to StackOverflow for visibility: https://stackoverflow.com/questions/69176875/can-amazon-connect-hours-of-operation-have-multiple-timezones (and anyone collecting SO "points" can get them) 😊

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
