### ISSUE TITLE
amazon connect play prompt from s3

### ISSUE THREAD

**Issue by gaurav-kishore** [awsdocs/amazon-connect-admin-guide#25]
i tried playing a prompt dynamically from s3 bucket by referring its ARN in contact flow attributes but its not getting played . 
Any support would be helpful

**Comment by m66rus** [comment]
Support for playing media files stored in S3 is on the roadmap, so currently it is not possible.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
