### ISSUE TITLE
sentiment score!

### ISSUE THREAD

**Issue by un-lock-me** [awsdocs/amazon-connect-admin-guide#26]
Hello,

Do you have any documentation for how to assign sentiment score to utterances? I'd like to know how the model assigns the score and specifically this part"frequency and proximity of the resulting sentiment for each speaker turn". I appreciate it if you could shed more light on it.

Thanks~

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
