### ISSUE TITLE
create_contact_flow content length

### ISSUE THREAD

**Issue by chrisdjin** [awsdocs/amazon-connect-admin-guide#28]
Issue: When the content length is greater than ~2000, the following error is generated:
An error occurred (InvalidContactFlowException) when calling the CreateContactFlow operation: None

response = client.create_contact_flow(
    InstanceId='string',
    Name='string',
    Type='CONTACT_FLOW'|'CUSTOMER_QUEUE'|'CUSTOMER_HOLD'|'CUSTOMER_WHISPER'|'AGENT_HOLD'|'AGENT_WHISPER'|'OUTBOUND_WHISPER'|'AGENT_TRANSFER'|'QUEUE_TRANSFER',
    Description='string',
    Content='string',
    Tags={
        'string': 'string'
    }
)

Sample outputs:

length: 9093
An error occurred (InvalidContactFlowException) when calling the CreateContactFlow operation: None

length: 365
{'ResponseMetadata': {'RequestId': 'xxx', 'HTTPStatusCode': 200, xxxx'}

Please advice

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
