### ISSUE TITLE
Errors in contact-events.md

### ISSUE THREAD

**Issue by mschersten** [awsdocs/amazon-connect-admin-guide#29]
There are some errors in this file:

* AgentInfo is capitalized in the sample contact events, in lines 183 and 220.
* AgentArn is capitalized in lines 184 and 221.
* The AgentInfo object does not actually provide the RoutingProfileArn.  This may be an error with the event rather than the documentation here, but the sample in line 220 shows the correct current format, without RoutingProfileArn.
* RoutingProfileArn should also presumably not be capitalized in the sample in line 185.
* The timestamps in lines 225-227 should be inside the "detail" object.
* In the events I'm seeing, a DISCONNECT event for an inbound voice call does not have a connectedToSystemTimestamp.

Thanks

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
