### ISSUE TITLE
Inaccuracy in Steps mentioned for "To Complete the  SpeakToAgent intent" and the corresponding the flow screenshot

### ISSUE THREAD

**Issue by Pavithradevadiga** [awsdocs/amazon-connect-admin-guide#30]
Page  in which the issue is present - [Add an Amazon Lex bot- Amazon connect](https://docs.aws.amazon.com/connect/latest/adminguide/amazon-lex.html) which explains on adding an Amazon bot to amazon connect.

At the end we see the steps to **Finish Contact Flow**

4 steps are mentioned under **To complete the SpeakToAgent intent** which is a part of **Finish Contact Flow**

We see that **set customer queue flow** is mentioned but not **set working queue**  before transfer to queue.

The same is followed in the screenshot **set working queue** block could not be found

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
