### ISSUE TITLE
Error in monitoring-cloudwatch.md

### ISSUE THREAD

**Issue by simon-hanmer** [awsdocs/amazon-connect-admin-guide#32]
The MissedCalls metric states that the unit is `Seconds`, however during testing, it seems to actually use `Count`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
