### ISSUE TITLE
DISCONNECT event not thrown if customer disconnects the call

### ISSUE THREAD

**Issue by Nithishsubramaiyan** [awsdocs/amazon-connect-admin-guide#38]
What event is thrown if the customer disconnect the call. 

I have checked the amazon connect event bus , as per the docs DISCONNECTED event is thrown only if the call is disconnected by the agent or flow action but need to know weather event is thrown if the customer disconnects the call within the flow.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
